version: '2'

services:
  mysql:
    image: mysql
    container_name: applitrami-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "applitrami"
      MYSQL_USER: "applitrami"
    volumes:
      - /storage/docker/applitrami-data:/var/lib/mysql