version: '2'

services:
    db:
      image: mysql
      environment:
                - MYSQL_DATABASE=applitrami
                - MYSQL_USER=applitrami
                - MYSQL_PASSWORD=password
                - MYSQL_ROOT_PASSWORD=password
                - MYSQL_ROOT_HOST=%
      volumes:
            - ./db_houseskipper:/var/lib/mysql
      ports:
            - "3306:3306"
    phpmyadmin:
     image: phpmyadmin/phpmyadmin
     environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: applitrami
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
     ports:
            - "80:80"
     links:
            # for mysql container
            - "db:db"
volumes:
    db:
        driver: "local"